baseURL = "http://example.org/"
languageCode = "en-us"
title = "petai"
theme = "kacang"
[author]
    name = "huje zaki"
    homepage = "https://twitter.com/ardiantapargo"
    bio = "Pengamat Langit"
    image = "https://lh5.googleusercontent.com/-h2tLsyijw8Q/AAAAAAAAAAI/AAAAAAAACys/WBpjN_34z3o/s32-c/photo.jpg"
